### ISSUE TITLE
MSDOS or FreeDOS does not boot under EMU86

### ISSUE THREAD

**Issue by cocus** [mfld-fr/emu86#30] opened 2021-04-29 00:04 UTC
Hi, I've hacked this project enough to support my weird board that I'm trying to use (80C188, 128k RAM, 512k FLASH, serial port, and I've added an SD card) so I don't have to remove the flash, burn it, and place it back on the board to test my code. Of course I'm not emulating all of the aspects of the 80C188, but close enough.
I've reached a point where my custom bios is able to provide enough system services to interact with the user, read disk, etc. 
Now I've tried to boot my own code, and it works perfectly. After that, I've tried to run DOS (MS-DOS 3.30, MS-DOS 6.22, FreeDOS) all of them from a 1.4MB floppy (emulated), but there's always an issue and it crashes. I'm not sure why tho, debugging it doesn't yield anything obvious. Both the MS DOS 3.30 and 6.22 usually crash after the DOS has been set up so it's providing the int21h, and I can see that it overwrites the entire BDA with gibberish.
Maybe you have some experiences running DOS on the emulator, or maybe one of my changes did break something, or even my BIOS is faulty or it's providing something that the DOS doesn't like.

Thanks!

**Comment by mfld-fr** [comment] 2021-04-29 06:50
Hello @cocus. As far as I know and before your try, EMU86 is only used in two cases : emulation for my own board (Advantech SNMP-1000, similar to your board) and emulation for [ELKS](https://github.com/jbruchon/elks) in a very minimal PC configuration. I never tried to boot xxxDOS, and I guess this is probably because that latest is expecting more that the current emulated things. May be you could try to check your BIOS against ELKS ?

**Comment by ghaerr** [comment] 2021-04-29 17:02
Hi @cocus,

> Both the MS DOS 3.30 and 6.22 usually crash after the DOS has been set up so it's providing the int21h

I assume you're talking about your hardware booting DOS, not EMU86. It would be worth a try to boot DOS from EMU86 to help debug where the system is failing. 

The configurable BIOS implementation in EMU86 is purposely minimal, supporting low level keyboard and terminal output, with floppy and HD I/O recently added for ELKS. EMU86 is very useful for testing exactly which BIOS entry points are required by ELKS, for porting and various hardware configurations, for instance. @mfld-fr's suggestion of trying to boot ELKS using your BIOS is a good idea as a next step.

> and I can see that it overwrites the entire BDA with gibberish.

EMU86's BIOS has no support for any BIOS Data Area (BDA) data, on purpose. DOS likely requires this. We can have more a discussion on this should this prove to be an issue.

Thank you!

**Comment by cocus** [comment] 2021-04-29 17:13
Hi @mfld-fr! I could try that, the problem is that I haven't tried ELKS before, and I think it's going to take me a lot of time to understand it.
In any case, I'll give it a try if I can't succeed in make DOS boot.
Hi @ghaerr! No, I'm trying to boot DOS under emu86, not on my actual hardware. I've removed all traces of the bios interrupt services so my own bios takes place. I should revert this back and try to boot DOS directly using that code.
I've also added some hooks on the memory reads, and I can tell that DOS doesn't read the BDA (except in ONE single occasion, and a single value).
My hardware (and emu86 as I've configured it for now) doesn't have any PC peripherals attached, which means that any IO operation (that's not aimed for the 80C188's internal peripheral block) is completely discarded. I assume that DOS and FreeDOS interact with the PIC at least, but I haven't checked. I don't know if having a PIC or some other peripheral is a requirement to boot DOS (I hope not!)
The problem seems to be that "something" doesn't work properly, and then DOS misbehaves and overwrites the entire BDA. FreeDOS on the other hand, just hangs on a certain part of its code where they have a jz, jg and jnb, and none of these conditions seems to be met. I haven't debugged much further with FreeDOS.
Thanks for your replies!

**Comment by ghaerr** [comment] 2021-04-29 17:27
> I've removed all traces of the bios interrupt services so my own bios takes place. I should revert this back and try to boot DOS directly using that code.

Yes, try using the original BIOS code; there are several places where unimplemented calls should produce an info message, similar to the memory read hooks you're using to see when the BDA segment its being read/written. The info messages should be very useful in seeing what DOS expects, at least while booting up.

> I don't know if having a PIC or some other peripheral is a requirement to boot DOS (I hope not!)

I would bet that DOS requires a PIC, but that is easily determined by observing when that port is read/written. IIRC, I left in code specifically to display info messages for just that.

> The problem seems to be that "something" doesn't work properly, and then DOS misbehaves and overwrites the entire BDA. FreeDOS on the other hand, just hangs on a certain part of its code where they have a jz, jg and jnb, and none of these conditions seems to be met.

This could easily be the result of a partially-implemented instruction in EMU86, specifically with the flags register settings. I have noted that there are quite a few instructions that have not yet implemented flags bits as the final part of their emulation. Tracing backwards (by running in "c" (continuous trace) mode) into a terminal and looking at previous instructions to the FreeDOS jz/jg/jnb might lead you to the culprit.

**Comment by cocus** [comment] 2021-04-29 17:33
> Yes, try using the original BIOS code; there are several places where unimplemented calls should produce an info message, similar to the memory read hooks you're using to see when the BDA segment its being read/written. The info messages should be very useful in seeing what DOS expects, at least while booting up.

Yes, that's how I checked for all the services that MSDOS and FreeDOS were expecting and the ones I had to implement. As far as I know, all the interrupts that emu86 shows when booting both of these DOS (except int 21h, which is the way to interact with dos) are handled, and with proper code (not just stubs). I've tested them with some dummy assembly code as well.

> I would bet that DOS requires a PIC, but that is easily determined by observing when that port is read/written. IIRC, I left in code specifically to display info messages for just that.

Seems like I took that code off when I added my own target :) It's a pretty horrible job I did to support the 80c188, and some parts of this platform, but I might end up pushing these changes to one of my repos.

> This could easily be the result of a partially-implemented instruction in EMU86, specifically with the flags register settings. I have noted that there are quite a few instructions that have not yet implemented flags bits as the final part of their emulation. Tracing backwards (by running in "c" (continuous trace) mode) into a terminal and looking at previous instructions to the FreeDOS jz/jg/jnb might lead you to the culprit.
Indeed, I'll have to check where these 3 instructions are, and set up a breakpoint. I've added support for multiple breakpoints (instead of a single one), and I might end up opening a PR for that change.

Thanks

**Comment by ghaerr** [comment] 2021-04-29 18:14
> I've added support for multiple breakpoints (instead of a single one), and I might end up opening a PR for that change.

A user-interface PR will likely affect my outstanding PR #27 which @mfld-fr has not had free time to evaluate. The emscripten/browser modifications are separate but I had to slightly change the main loop to work with emscripten requirements. Perhaps the main loop change should be unbundled from that PR so that our PR's don't get out of sync...  ?

**Comment by cocus** [comment] 2021-04-29 18:25
> A user-interface PR will likely affect my outstanding PR #27 which @mfld-fr has not had free time to evaluate. The emscripten/browser modifications are separate but I had to slightly change the main loop to work with emscripten requirements. Perhaps the main loop change should be unbundled from that PR so that our PR's don't get out of sync... ?
Ah, don't worry then! I'll keep my changes and rebase them once your PR goes thru. I would like to have the serial output of the emulator decoupled of the debug "console", and make it a little bit more user friendly :)

**Comment by mfld-fr** [comment] 2021-04-29 21:12
> I would like to have the serial output of the emulator decoupled of the debug "console", and make it a little bit more user friendly :)

You can change the serial backend with `SERIAL=pty` in the Makefile, then use `pcat` to connect to that PTY. That way you have the EMU86 debug console and the serial console decoupled, and it also helps for automatic testing:
```
emu86 -w 0x80000 -f ../../img/ADVTECH1.BIN -w 0xf8100 -f mon86.bin &
sleep 10
pcat -t 1000 -d 1 `cat emu86.pts` < ../test-mon86-in.txt > test-emu-out.txt
diff ../test-mon86-ref.txt test-emu-out.txt
```

Also feel free to submit any PR at any time, I would take over and rebase if necessary if the PR looks valuable.

**Comment by mfld-fr** [comment] 2021-05-02 08:50
Hello @cocus, @ghaerr and I made the things clear and ready to accept any incoming MR. For example, I would be **very** interested in your 80188 internal devices emulation (chip select, PIC, PIT, DMA), even in draft state, to compare with the R8810 clone used in my SBC. Please tell me if you would have any more question or if I could close this issue now ? Thanks !

**Comment by cocus** [comment] 2021-05-02 15:10
Hello all, I didn't have enough time to run the tests mentioned to check if DOS is not booting because of my BIOS or because another factor. Let me try to do that and I will will document my findings.
I forgot to mention that I knew about the pty console output, but the issue was that I find it to be a chore to debug it using vscode. But that's my own issue though.
Regarding the 80188 emulated peripheral stuff, I only have the serial port and the PCB block (not even the timers) emulated. As far as I know, there's no DMA nor PIC (well, there's something similar, but not particularly the same) integrated in them. But I will share my changes once I feel they "work" a little bit better. Thanks

**Comment by mfld-fr** [comment] 2021-05-02 15:21
Okay, so looking forward for any news, and closing this one for now. Thanks !

**Comment by mfld-fr** [comment] 2021-05-06 08:00
I just had a look to @cocus fork and the 80188 HW emulation. We can forget the idea to test ELKS on @cocus BIOS, because ELKS accesses directly some PC peripherals like the 8259 PIC and the 8253/54 PIT, while these devices are integrated in the 80188 PCB, and so the I/O mapping is not the same (before any other difference in their registers).

For example, the 80188 PIC registers are mapped to 0xFF02-0xFF20, while the 8259 PIC registers are mapped to 0x0020-0x0022.

More generally, any OS that would access directly the HW and not going through the customized BIOS would fail to operate on such platform without the right drivers. I have the same problem on my SBC because I still have to rewrite some parts of ELKS to handle the integrated peripherals (R8810 is a 80188 clone, but again with a different PCB).

I still don't know whether xxxDOS does such direct access or not, and I am sorry to have no time to investigate that point by trying to boot that OS on EMU86 :disappointed:

**Comment by cocus** [comment] 2021-05-06 13:50
Hi @mfld-fr, thanks for having a look at the code. I've checked that xxDOS doesn't interact with the peripherals at all (at least until this part of the execution where it crashes). The only thing writing to an "unhandled" IO region on the emu86 is my BIOS, when toggling some LEDs.
I'm strongly suspecting a rogue opcode handler. I might be able to debug some more today

**Comment by ghaerr** [comment] 2021-05-06 15:44
> I have the same problem on my SBC because I still have to rewrite some parts of ELKS to handle the integrated peripherals (R8810 is a 80188 clone, but again with a different PCB).

Is this rewrite just changing port addresses, or is the hardware significantly different? Are we talking only about PIC and PIT, or is there more?

We have a somewhat configurable mechanism in ELKS for these kinds of things (ports.h, not .config). I'm wondering whether something similar should be used in EMU86, for the same reasons?

**Comment by mfld-fr** [comment] 2021-05-06 17:16
Device registers are significantly different, as you can see in EMU86, but logical functions are quite the same. Only the Ethernet adapter is ISA-NE2K compatible, this is why porting its driver to ELKS in 2015 was quite straightforward.

**Comment by mfld-fr** [comment] 2021-05-07 17:14
Re-opening this issue: I tried to boot the `fd.img` from '8086tiny' that is based on FreeDOS, and EMU86 quickly fails in the boot sector. I modified the INT13h handler to break on first disk error, and I got the following traces:
```
info: disk image fd.img (DCHS 1/80/2/18)
INT 13h AH=2h: Invalid DCHS 0/0/1/2
```

The drive number after loading the image looks not good.

**Comment by ghaerr** [comment] 2021-05-07 17:26
Github seems to have lost your last message, but I think the problem is on line 242 in rom-elks.c:
```
if (find_drive (d)) d++;
```

There is a reason I added that when developing this for ELKS, having to do with handling multiple -I parameters. I will investigate later today.

**Comment by mfld-fr** [comment] 2021-05-07 17:27
Forget it, mistake from my own, I was not based on the latest commit. Sorry for the noise.

**Comment by mfld-fr** [comment] 2021-05-07 19:57
So after rebasing to get the latest fix on the disk image load, I tried to run EMU86 with the floppy image `fd.img` provided in '8086tiny', that does contain FreeDOS. The emulator stops on an ESC instruction, that is not valid without a 8087. On startup, just after moving some blocks around, the FreeDOS kernel uses a kind of transformation routine (decompression ?) on itself with many bit manipulations. This routine bugs after a few iterations and starts to source data from the vector table, that is clearly a wrong behavior. After executing step by step this routine, I came to the following:
```
AX A8A0  BX 804F  CX 0000  DX 074E  FL 0201
SI 0000  DI 0000  IP 0005  SP 01FC  BP 0005
DS 074E  ES 0060  CS 1254  SS 1254

CF 1  PF 0  AF 0  ZF 0  SF 0  TF 0  IF 1  DF 0  OF 0

1254:0005  00 FF              ADD     BH,BH
>  
AX A8A0  BX 004F  CX 0000  DX 074E  FL 0A01
SI 0000  DI 0000  IP 0007  SP 01FC  BP 0005
DS 074E  ES 0060  CS 1254  SS 1254

CF 1  PF 0  AF 0  ZF 0  SF 0  TF 0  IF 1  DF 0  OF 1

1254:0007  75 03              JNZ     000Ch
>
```

BH was 80h before the `ADD BH,BH`, so the resulting BH to 00h is correct, but the ZF flag should be 1, and it actually stays to 0.

**Comment by mfld-fr** [comment] 2021-05-07 20:21
After fixing the ZF flag for 8 bits addition:
```
mfld@home /mnt/data/home/mfld/advantech/emu86 $ ./emu86 -I fd.img
info: disk image fd.img (DCHS 0/80/2/18)
FreeDOS kernel - SVN (build 2040 OEM:0xfd) [compiled Apr  7 2012]
Kernel compatibility 7.10 - WATCOMC - FAT32 support

(C) Copyright 1995-2011 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
fatal: no handler for INT 11h
error: execute operation
AX C78D  BX 2328  CX 0000  DX 0000  FL 0200
SI 0070  DI 234C  IP A11C  SP 230C  BP 0070
DS FFFE  ES 0606  CS 7001  SS 7DCA

CF 0  PF 0  AF 0  ZF 0  SF 0  TF 0  IF 1  DF 0  OF 0

7001:A11C  CD 11              INT     11h
>
```

**Comment by ghaerr** [comment] 2021-05-07 20:45
Nice work debugging the ZF flag bug in the 8-bit add instruction!

If you add INT 11h (BIOS equipment list), I will add the BDA emulation portion of that at 0040:0010h as part of video text emulation PR #50. Or if you like, I will add INT 11h to try to move FreeDOS boot support forward in testing EMU86.

> On startup, just after moving some blocks around, the FreeDOS kernel uses a kind of transformation routine (decompression ?) on itself with many bit manipulations.

I'm pretty sure this is the Exomizer decompressor, recently added to ELKS for compressed executables. There had been some discussion that FreeDOS uses it also.

Thanks for testing the BIOS INT 13h against another OS, that helps verify it is correct.

**Comment by cocus** [comment] 2021-05-07 22:27
Wow! Amazing work @mfld-fr! I will have a look at booting msdos after you merge your changes.

@ghaerr I started adding some dummy bios services last night to get msdos booting, at least to the same extent as with my bios. Int 11, 15, 14 and some others are needed. Most of them just return some values from the BDA, which is currently missing altogether. In theory we could hardcode the values instead of setting them up in the bda for now, for instance one of these ints queries the memory size, but in this situation we should return 640, since there's no support for ems or such; the int related to the equipment flags is usually 0x41, etc. I've validated that msdos (at least until the point it crashed on my last runs) didn't check for the bda at all.

**Comment by ghaerr** [comment] 2021-05-07 22:45
> Int 11, 15, 14 and some others are needed.

INT 11h was just written by @mfld-fr and committed.
INT 15h is at least partly implemented already.
INT 12h returns the available memory, which is set to 512K for now to allow for easy ROM filesystem insertion at 0x80000.

> Most of them just return some values from the BDA, which is currently missing altogether. 

My PR #50 implements the beginning of BDA emulation. It should be ready for merge very soon.

> In theory we could hardcode the values instead of setting them up in the bda for now

I definitely recommend that, since we don't want to emulate more of the BDA than we have to. PR #50 is implementing certain BDA offsets *only because it has to*. It does not implement BDA for items that can be returned via INT. See @mfld-fr's recent INT 11h implementation (committed) for instance.

> the int related to the equipment flags is usually 0x41, etc.

I recommend that you add the required INT functions that are needed to boot MSDOS, and not the BDA, then submit a PR.

> I've validated that msdos (at least until the point it crashed on my last runs) didn't check for the bda at all.

That's good news, as EMU86 isn't likely to turn into a full-fledged PC emulator, but stay small so that it can be best used for its intended purpose in embedded targets.

Thank you!

**Comment by cocus** [comment] 2021-05-07 23:46
Well, I've managed to get it to an A:\> prompt, but it doesn't process my keyboard input at all. This is pretty good!
Sadly it doesn't reach that far with my BIOS, so I'll have to double check what's going on there.
I'll push my changes later.
(Also note, I've silenced some INTs on the debug, since they were showing up so often).

```
info: code breakpoint address 27BE9h
info: code breakpoint address 07C00h
info: code breakpoint address FFFF0h
info: code breakpoint 2 hit
AX 0000  BX 0000  CX 0000  DX 0000  FL 0000
SI 0000  DI 0000  IP FFF0  SP 0000  BP 0000
DS 0000  ES 0000  CS F000  SS 0000

CF 0  PF 0  AF 0  ZF 0  SF 0  TF 0  IF 0  DF 0  OF 0

F000:FFF0  EA 00 00 00 F0     jmpf    0xf000:0x0000
>g
[INT 19h AX=0000 DX=0000 from f000:0002]
[INT feh AX=0000 DX=0000 from f000:3002]
info: code breakpoint 1 hit
AX 0000  BX 0000  CX 0000  DX 0000  FL 0000
SI 0000  DI 0000  IP 7C00  SP FFFA  BP 0000
DS 0000  ES 0000  CS 0000  SS 0000

CF 0  PF 0  AF 0  ZF 0  SF 0  TF 0  IF 0  DF 0  OF 0

0000:7C00  EB 3C              jmp     7c3e
>g
[INT 12h AX=0000 DX=0000 from 0070:01eb]
Iniciando MS-DOS...

[INT 11h AX=ffff DX=0000 from 0070:1873]
[INT 15h AX=c000 DX=0000 from 0070:18d8]
[INT 14h AX=00a3 DX=0003 from 0070:22ae]
[INT 14h AX=00a3 DX=0002 from 0070:22ae]
[INT 14h AX=00a3 DX=0001 from 0070:22ae]
[INT 14h AX=00a3 DX=0000 from 0070:22ae]
[INT 17h AX=0102 DX=0002 from 0070:22a4]
[INT 17h AX=0101 DX=0001 from 0070:22a4]
[INT 17h AX=0100 DX=0000 from 0070:22a4]
[INT 12h AX=0000 DX=0000 from 0070:1997]
info: BDA read byte 0xff (496h) from 0070:1a1f
[INT 15h AX=4101 DX=0002 from 0070:1ce5]
[INT 15h AX=c009 DX=00de from 0474:0420]
[INT 11h AX=f0ff DX=00de from 0474:0447]
[INT 15h AX=880e DX=bdc8 from 6eb5:05e5]
[INT 15h AX=c000 DX=02f7 from 6eb5:1153]

A:\>

A:\>
```

**Comment by cocus** [comment] 2021-05-08 01:23
@mfld-fr I've tried the latest FreeDOS as well, [1.3-rc4](https://www.ibiblio.org/pub/micro/pc-stuff/freedos/files/distributions/1.3/previews/1.3-rc4/). Sadly it crashes a little bit before than your example, not sure why. Here's the output:
![Screenshot from 2021-05-07 22-22-53](https://user-images.githubusercontent.com/523726/117521183-d63f1600-af82-11eb-987a-443617957f18.png)
Maybe there's something else going on here, but it's a relief that MS-DOS boots.

**Comment by mfld-fr** [comment] 2021-05-08 07:08
Nice to see MSDOS booting under EMU86 😄 !

**Comment by mfld-fr** [comment] 2021-05-09 10:11
Now FreeDOS boots :smile: !
```
mfld@home /mnt/data/home/mfld/advantech/emu86 $ ./emu86 -I fd.img
info: disk image fd.img (DCHS 0/80/2/18)
FreeDOS kernel - SVN (build 2040 OEM:0xfd) [compiled Apr  7 2012]
Kernel compatibility 7.10 - WATCOMC - FAT32 support

(C) Copyright 1995-2011 Pasquale J. Villani and The FreeDOS Project.
All Rights Reserved. This is free software and comes with ABSOLUTELY NO
WARRANTY; you can redistribute it and/or modify it under the terms of the
GNU General Public License as published by the Free Software Foundation;
either version 2, or (at your option) any later version.
 - InitDiskwarning: INT 13h AH=15h: no DASD type
warning: INT 13h AH=15h: no DASD type
no hard disks detected
                                                                               
FreeCom version 0.82 pl 3 XMS_Swap [Dec 10 2003 06:49:21]


 type HELP to get support on commands and navigation

A:\>dir
 Volume in drive A is FREEDOS1
 Volume Serial Number is 4559-120D
 Directory of A:\

KERNEL   SYS        45,450  04-07-2012  8:13a
COMMAND  COM        66,090  12-10-2003  7:49a
CONFIG   SYS           734  02-13-2014  9:06p
AUTOEXEC BAT           894  01-19-2014  2:04a
FREEDOS              <DIR>  10-07-2006 10:56a
APPINFO  TGZ        11,021  10-11-2006  3:00p
QUITEMU  COM             5  06-19-2013  4:35p
ALLEYCAT EXE        55,067  08-26-1998  2:52p
         7 file(s)        179,261 bytes
         1 dir(s)          57,344 bytes free

A:\>
```

**Closed** 2021-05-10 16:17 UTC
Labels: bug

**Comment by cocus** [comment] 2021-05-10 20:01
Thanks for this guys! I've been really busy these last days and I couldn't add any changes or comments. Thanks again!
